source:
  cat_fn: '/global/cfs/cdirs/desi/users/boryanah/reconstruction_DESI/recon/catalog_BGS_BRIGHT-20.2_R12.50_nmesh512_recsym_MG_cigale_masked.fits'

processing:
  cat_type: 'BGS'
  # filter_type: 'no_src_with_cluster_mask' # 'unfiltered', 'no_src_with_cluster_mask', or 'nopairs'
  filter_type: 'nopairs' # 'unfiltered', 'no_src_with_cluster_mask', or 'nopairs'
  physical_sep: 0.5 # in unit of Mpc, only used when filter_type is 'nopairs'
  zbins:
    - [0.1, 0.2]
    - [0.2, 0.3]
    - [0.3, 0.4]


save:
  save_dir: '/pscratch/sd/r/rhliu/projects/Weak_lensing/desi/spec_Y3/BGS_CIGALE/'
  save_format: 'csv' # 'csv' or 'txt'
